### ISSUE TITLE
Unibeautify CI doesn't work when branch is in another repo

### ISSUE THREAD

**Issue by stevenzeck** [Unibeautify/ci-issues#1]
When opening PR's against the main repository, if your PR branch exists in a different repository (such as a forked one), Unibeautify CI does not run.

**Comment by Glavin001** [comment]
@stevenzeck I think I've fixed this. Have you seen this problem recently? If so, please provide a link.

**Comment by Glavin001** [comment]
Closing. If it happens again let's reopen.
